routes/web.php
<?php

use App\Http\Controllers\DepartmentsController;
use App\Http\Controllers\EmployeesController;
use App\Http\Controllers\PayrollsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\UsersController;
use App\Models\Department;
use App\Models\Employee;
use App\Models\Payroll;
use App\Models\Role;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::middleware(['auth'])->group(function() {
    Route::get('/dashboard', function() {
        return view('dashboard', [
            'payrollsCount' => Payroll::all()->count(),
            'employeesCount' => Employee::all()->count(),
            'rolesCount' => Role::all()->count(),
            'departmentsCount' => Department::all()->count(),
            'latestEmployees' => Employee::latest()->take(5)->get(),
            'latestPayrolls' => Payroll::latest()->take(5)->get()
        ]);
    })->name('dashboard')->middleware(['dashboard']);
    Route::resource('departments', DepartmentsController::class)->except(['create', 'show', 'edit'])->middleware(['departments']);
    Route::resource('roles', RolesController::class)->except(['create', 'show', 'edit'])->middleware(['roles']);
    Route::middleware(['employees'])->group(function() {
        Route::put('employees/edit-bulk', [EmployeesController::class, 'updateBulk'])->name('employees.edit.bulk');
        Route::delete('employees/delete-bulk', [EmployeesController::class, 'destroyBulk'])->name('employees.destroy.bulk');
        Route::resource('employees', EmployeesController::class)->except(['create', 'show', 'edit']);
    });
    Route::resource('users', UsersController::class)->only(['update']);
    Route::get('profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::post('profile/update/avatar', [ProfileController::class, 'updateAvatar'])->name('profile.update.avatar');
    Route::put('profile/update', [ProfileController::class, 'update'])->name('profile.update');
    Route::apiResource('payrolls', PayrollsController::class)->only(['update', 'destroy']);
});

app/Models/User.php
<?php

namespace App\Models;

use App\Http\Traits\UsesUuid;
use Carbon\Carbon;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes, UsesUuid;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $primaryKey = 'id';

    public function role() {
        return $this->belongsTo(Role::class, 'role', 'title');
    }

    public function employee() {
        return $this->hasOne(Employee::class, 'user_id', 'id');
    }

    public function getCreatedAtAttribute($value) {
        return Carbon::parse($value)->toFormattedDateString();
    }
}

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('header_title')
<h1 class="m-0" style="color: var(--primary)">Dashboard</h1>
<hr style="background-color: var(--primary)">
@stop

@section('content')
<div class="container">
    <div class="row">
        <div class="col-6 col-sm-3">
            <div class="card card-outline">
                <div class="card-header text-center">Payrolls Issued</div>
                <div class="card-body text-center">
                    <h2>{{$payrollsCount}}</h2>
                </div>
            </div>
        </div>
        <div class="col-6 col-sm-3">
            <div class="card card-outline">
                <div class="card-header text-center">Employee Count</div>
                <div class="card-body text-center">
                    <h2>{{$employeesCount}}</h2>
                </div>
            </div>
        </div>
        <div class="col-6 col-sm-3">
            <div class="card card-outline">
                <div class="card-header text-center">Roles</div>
                <div class="card-body text-center">
                    <h2>{{$rolesCount}}</h2>
                </div>
            </div>
        </div>
        <div class="col-6 col-sm-3">
            <div class="card card-outline">
                <div class="card-header text-center">Departments</div>
                <div class="card-body text-center">
                    <h2>{{$departmentsCount}}</h2>
                </div>
            </div>
        </div>
    </div>
    <hr style="background-color: var(--primary);width: 50%">
    <div class="row mt-4">
        <div class="col-12">
            <div class="card">
                <div class="card-header">Latest Employees</div>
                <div class="card-body table-responsive">
                    <table class="table table-hover bg-white">
                        <thead class="text-center">
                            <tr>
                                <th>Date Added</th>
                                <th>Name</th>
                                <th>Email</th>  
                                <th>Position</th>
                                <th>Department</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                            @foreach($latestEmployees as $employee)
                                <tr>
                                    <td>{{$employee->created_at}}</td>
                                    <td>{{$employee->user->name}}</td>
                                    <td>{{$employee->user->email}}</td>
                                    <td>{{$employee->position}}</td>
                                    <td>{{$employee->department}}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <hr style="background-color: var(--primary);width: 50%">
    <div class="row mt-4">
        <div class="col-12">
            <div class="card">
                <div class="card-header">Latest Payrolls Issued</div>
                <div class="card-body table-responsive">
                    <table class="table table-hover bg-white">
                        <thead class="text-center">
                            <tr>
                                <th>Date Issued</th>
                                <th>Name</th>
                                <th>Overtime</th>
                                <th>Hours</th>
                                <th>Rate</th>
                                <th>Gross</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                            @foreach($latestPayrolls as $payroll)
                                <tr>
                                    <td>{{$payroll->created_at}}</td>
                                    <td>{{$payroll->employee->user->name}}</td>
                                    <td>{{$payroll->is_overtime ? 'Yes' : 'No'}}</td>
                                    <td>{{$payroll->hours}}</td>
                                    <td>{{$payroll->rate}}</td>
                                    <td>{{$payroll->gross}}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('styles')
<style>
    .card-header {
        background-color: var(--tertiary);
        color: var(--primary);
    }

    .card-body h2 {
        color: var(--quaternary);
    }
</style>
@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('title')
Empayroll | Home
@stop

@section('content')
<div class="container">
    <div class="jumbotron jumbotron-fluid bg-transparent">
        <div class="container align-content-center align-items-center">
            <div class="row">
                <div class="col-12 text-center justify-content-center">
                    <h1 class="display-2 text-white">Employee</h1>
                    <h2 class="dipslay-3">Payroll System</h2>
                </div>
            </div>
        </div>
      </div>
</div>
@endsection

@section('styles')
<style>
    .content-wrapper {
        background-color: white;
        background-image: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)),url('images/home-bg.jpg');
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>
@stop