routes/web.php
<?php

use App\Http\Controllers\DepartmentsController;
use App\Http\Controllers\EmployeesController;
use App\Http\Controllers\PayrollsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\UsersController;
use App\Models\Department;
use App\Models\Employee;
use App\Models\Payroll;
use App\Models\Role;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::middleware(['auth'])->group(function() {
    Route::get('/dashboard', function() {
        return view('dashboard', [
            'payrollsCount' => Payroll::all()->count(),
            'employeesCount' => Employee::all()->count(),
            'rolesCount' => Role::all()->count(),
            'departmentsCount' => Department::all()->count(),
            'latestEmployees' => Employee::latest()->take(5)->get(),
            'latestPayrolls' => Payroll::latest()->take(5)->get()
        ]);
    })->name('dashboard')->middleware(['dashboard']);
    Route::resource('departments', DepartmentsController::class)->except(['create', 'show', 'edit'])->middleware(['departments']);
    Route::resource('roles', RolesController::class)->except(['create', 'show', 'edit'])->middleware(['roles']);
    Route::middleware(['employees'])->group(function() {
        Route::put('employees/edit-bulk', [EmployeesController::class, 'updateBulk'])->name('employees.edit.bulk');
        Route::delete('employees/delete-bulk', [EmployeesController::class, 'destroyBulk'])->name('employees.destroy.bulk');
        Route::resource('employees', EmployeesController::class)->except(['create', 'show', 'edit']);
    });
    Route::resource('users', UsersController::class)->only(['update']);
    Route::get('profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::post('profile/update/avatar', [ProfileController::class, 'updateAvatar'])->name('profile.update.avatar');
    Route::put('profile/update', [ProfileController::class, 'update'])->name('profile.update');
    Route::apiResource('payrolls', PayrollsController::class)->only(['update', 'destroy']);
});

app/Models/Employee.php
<?php

namespace App\Models;

use App\Http\Traits\UsesUuid;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use HasFactory, SoftDeletes, UsesUuid;

    protected $guarded = [];
    protected $primaryKey = 'id';

    public function department() {
        return $this->belongsTo(Department::class, 'department', 'name');
    }

    public function user() {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function payrolls() {
        return $this->hasMany(Payroll::class, 'employee_id', 'id');
    }

    public function getCreatedAtAttribute($value) {
        return Carbon::parse($value)->toFormattedDateString();
    }
}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Department;
use App\Models\Employee;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class EmployeesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('employees.index', [
            'employees' => Employee::with(['user', 'payrolls'])->get(),
            'departments' => Department::orderBy('name')->get(),
            'roles' => Role::orderBy('title')->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $employee->update($request->except(['_token', '_method']));

        return redirect(route('employees.index'))->with('alert', [
            'type' => 'success',
            'message' => 'Employee successfully updated!'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
    }

    public function updateBulk(Request $request) {
        $updateParams = [];
        if (isset($request->position)) {
            $updateParams['position'] = $request->position;
        }
        if (isset($request->department)) {
            $updateParams['department'] = $request->department;
        }
        Employee::whereIn('id', $request->checkedEmployees)->update($updateParams);
    }

    public function destroyBulk(Request $request) {
        Employee::whereIn('id', $request->checkedEmployees)->get()->each(function($employee) {
            $employee->user()->delete();
            $employee->payrolls()->delete();
        });
        Employee::whereIn('id', $request->checkedEmployees)->delete();
    }
}

resources/views/employees/edit-bulk.blade.php
<div class="modal fade" id="editBulkEmployeeModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header bg-gradient-warning">
          <h4 class="modal-title">Edit Employees</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="POST" class="container" id="editBulkForm">
            @csrf
            @method('PUT')
            <div class="modal-body">
                <div class="row">
                    <div class="col-12">
                        <div class="my-3">Update Employees by:</div>
                        <div class="form-group">
                            <label for="editBulkPosition">Position:</label>
                            <input type="text" class="form-control" id="editBulkPosition"
                                placeholder="Enter position">
                        </div>
                        <div class="form-group">
                            <label for="editBulkDepartment">Department:</label>
                            <select name="editBulkDepartment" id="editBulkDepartment" class="form-control select2">
                                <option value="" disabled selected>Select Department</option>
                                @foreach($departments as $department)
                                    <option value="{{$department->name}}">{{$department->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-warning" onclick="onSubmitEditBulk()">
                    Submit
                </button>
            </div>
        </form>
      </div>
    </div>
  </div>

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('title')
Empayroll | Employees
@stop

@section('header_title')
<h1 class="m-0" style="color: var(--primary)">Employees</h1>
<hr style="background-color: var(--primary)">
@stop

@section('content')

@include('employees.show')
@include('employees.edit-bulk')

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="btn-group d-none" id="bulkActionsDropdown">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            Bulk Actions
                        </button>
                        <div class="dropdown-menu">
                          <button class="dropdown-item" onclick="onBulkAction('UPDATE')">Update</button>
                          <button class="dropdown-item" onclick="onBulkAction('DELETE')">Delete</button>
                        </div>
                    </div>
                </div>
                <div class="card-body table-responsive">
                    <table class="table table-hover bg-white" id="employeeTable">
                        <thead class="text-center">
                            <tr>
                                <th style="max-width: 100px">#</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Position</th>
                                <th>Department</th>
                                <th>Role</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                            @foreach($employees as $employee)
                                <tr>
                                    <td>
                                        @if (auth()->user()->id != $employee->user->id)
                                            <div class="icheck-primary d-flex align-content-center align-items-center justify-content-center">
                                                <input type="checkbox" id="employeeCheckbox{{$loop->index}}"
                                                    onchange="employeeChecked('{{$employee->id}}')">
                                                <label for="employeeCheckbox{{$loop->index}}"></label>
                                            </div>
                                        @endif
                                    </td>
                                    <td>{{$employee->user->name}}</td>
                                    <td>{{$employee->user->email}}</td>
                                    <td>{{$employee->position}}</td>
                                    <td class="d-flex justify-content-center">
                                        @if (auth()->user()->id != $employee->user->id)
                                            <form action="{{route('employees.update', $employee->id)}}" method="POST"
                                                id="employeeEditDepartmentForm{{$loop->index}}">
                                                @csrf
                                                @method('PUT')
                                                <select name="department" class="form-control select2"
                                                    onchange="changeDepartment('{{$loop->index}}')">
                                                    @foreach($departments as $department)
                                                        <option value="{{$department->name}}"
                                                            @if($employee->department == $department->name) selected @endif>
                                                            {{$department->name}}
                                                        </option>
                                                    @endforeach
                                                </select>
                                            </form>
                                        @else
                                            {{$employee->department}}
                                        @endif
                                    </td>
                                    <td>
                                        @if (auth()->user()->id != $employee->user->id)
                                            <form action="{{route('users.update', $employee->user->id)}}" method="POST"
                                                id="employeeEditRoleForm{{$loop->index}}">
                                                @csrf
                                                @method('PUT')
                                                <select name="role" class="form-control select2"
                                                    onchange="changeRole('{{$loop->index}}')">
                                                    @foreach($roles as $role)
                                                        <option value="{{$role->title}}"
                                                            @if($employee->user->role == $role->title) selected @endif>
                                                            {{$role->title}}
                                                        </option>
                                                    @endforeach
                                                </select>
                                            </form>
                                        @else
                                            {{$employee->user->role}}
                                        @endif
                                    </td>
                                    <td>
                                        <span data-toggle="tooltip" data-placement="top" title="View">
                                            {{-- <button class="btn btn-primary rounded-circle m-1 btn-sm"
                                                data-toggle="modal" data-target="#showEmployeeModal"
                                                onclick="showEmployee('{{$employee->id}}')">
                                                <i class="far fa-eye"></i>
                                            </button> --}}
                                            <a href="{{route('profile.index', ['id' => $employee->user->id])}}" class="btn btn-primary rounded-circle m-1 btn-sm">
                                                <i class="far fa-eye"></i>
                                            </a>
                                        </span>
                                        @if($employee->user->id != auth()->user()->id)
                                            <span data-toggle="tooltip" data-placement="top" title="Delete">
                                                <button class="btn btn-danger rounded-circle m-1 btn-sm"
                                                    onclick="deleteEmployee('{{$employee->id}}')">
                                                    <i class="far fa-trash-alt"></i>
                                                </button>
                                            </span>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('styles')
<style>
    .dropdown-item:hover, .dropdown-item:focus{
        background-color: var(--tertiary) !important;
        color: var(--primary) !important;
    }
</style>
@stop

@section('scripts')
<script>
    let checkedEmployees = [];
    $('#employeeTable').DataTable();

    function showEmployee(id) {
        let employees = {!! $employees !!};
        employee = employees.find(employee => employee.id == id);
        if (employee.avatar_url) {
            $('#userPhoto').attr('src', 'storage/' + employee.avatar_url);
        } else {
            $('#userPhoto').attr('src', '{{asset('images/noimage.jpg')}}');
        }
        $('#showEmployeeInfo').children()[1].textContent = employee.user.name;
        $('#showEmployeeInfo').children()[3].textContent = employee.user.email;
        $('#showEmployeeInfo').children()[5].textContent = employee.position;
        $('#showEmployeeInfo').children()[7].textContent = employee.department;
        $('#showEmployeeInfo').children()[9].textContent = employee.user.role;
        $('#showEmployeeInfo').children()[11].textContent = employee.about_me;
        $('#showEmployeeTable').DataTable().clear().destroy();
        employee.payrolls.forEach(payroll => {
            let checkbox = $('<td>' + 1 + '</td>');
            let name = $('<td>' + payroll.created_at +'</td>');
            let overtime = $('<td>' + (payroll.is_overtime == '1' ? 'Yes' : 'No') +'</td>');
            let hours = $('<td>' + payroll.hours +'</td>');
            let rate = $('<td>' + payroll.rate +'</td>');
            let gross = $('<td>' + payroll.gross +'</td>');
            let newRow = $('<tr></tr>');
            $('#showEmployeeTable tbody').append(newRow);
            newRow
                .append(name)
                .append(overtime)
                .append(hours)
                .append(rate)
                .append(gross);
        });
        $('#showEmployeeTable').DataTable();
    }

    function deleteEmployee(id) {
        Swal.fire({
            title: 'Are you sure?',
            text: "Only privileged users can revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3d5af1',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.value) {
                axios.delete('{{route('home')}}' + '/employees/' + id).then(() => {
                    Swal.fire(
                        'Deleted!',
                        'Employee has been deleted.',
                        'success'
                    )
                    location.reload();
                });
            }
        })
    }

    function changeDepartment(index) {
        $('#employeeEditDepartmentForm' + index).submit();
    }

    function changeRole(index) {
        $('#employeeEditRoleForm' + index).submit();
    }

    function employeeChecked(id) {
        if (checkedEmployees.find(ids => ids == id)) {
            let index = checkedEmployees.findIndex(ids => ids == id)
            checkedEmployees.splice(index, 1);
        } else {
            checkedEmployees.push(id);
        }
        if (checkedEmployees.length > 0) {
            if ($('#bulkActionsDropdown').hasClass('d-none')) {
                $('#bulkActionsDropdown').removeClass('d-none');
            }
        } else {
            if (! $('#bulkActionsDropdown').hasClass('d-none')) {
                $('#bulkActionsDropdown').addClass('d-none');
            }
        }
    }

    function onBulkAction(action) {
        switch(action) {
            case 'UPDATE':
                $('#editBulkEmployeeModal').modal('show');
                break;
            case 'DELETE':
                Swal.fire({
                    title: 'Are you sure?',
                    text: "Only Admins can revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3d5af1',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete them!'
                }).then((result) => {
                    if (result.value) {
                        axios.delete('{{route('employees.destroy.bulk')}}', {
                            data: {
                                checkedEmployees: checkedEmployees
                            }
                        })
                            .then(() => {
                                Swal.fire(
                                    'Deleted!',
                                    'The Employees were deleted.',
                                    'success'
                                )
                                window.location.href = '{{route('employees.index')}}';
                            })
                            .catch(error => {
                                Toast.fire({
                                    icon: "error",
                                    title: error.message
                                });
                            });
                    }
                })
                break;
        }
    }

    function onSubmitEditBulk() {
        axios.put('{{route('employees.edit.bulk')}}', {
            checkedEmployees: checkedEmployees,
            position: $('#editBulkPosition').val(),
            department: $('#editBulkDepartment option:selected').text()
        })
            .then(() => {
                Toast.fire({
                    icon: "success",
                    title: "Employees were successfully updated!"
                });
                $('#editBulkEmployeeModal').modal('hide');
                $('#editBulkForm').trigger('reset');
                window.location.href = '{{route('employees.index')}}';
            })
            .catch(error => {
                Toast.fire({
                    icon: "error",
                    title: error.message
                });
            });
    }
</script>
@stop

resources/views/employees/show.blade.php
<div class="modal fade" id="showEmployeeModal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header bg-primary">
          <h4 class="modal-title">View Employee</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="container">
            <h4 class="text-center">Details</h4>
            <hr style="background-color: var(--secondary)">
            <div class="row justify-content-center mx-5">
              <div class="col-12 col-sm-4">
                <img src="" alt="avatar" id="userPhoto" class="img-fluid img-thumbnail">
              </div>
              <div class="col-12 col-sm-8 pl-4">
                <dl class="row" id="showEmployeeInfo">
                  <dt class="col-sm-3">Name:</dt>
                  <dd class="col-sm-9" style="color: var(--quaternary)"></dd>
                  <dt class="col-sm-3">Email:</dt>
                  <dd class="col-sm-9" style="color: var(--quaternary)"></dd>
                  <dt class="col-sm-3">Position:</dt>
                  <dd class="col-sm-9" style="color: var(--quaternary)"></dd>
                  <dt class="col-sm-3">Department:</dt>
                  <dd class="col-sm-9" style="color: var(--quaternary)"></dd>
                  <dt class="col-sm-3">Role:</dt>
                  <dd class="col-sm-9" style="color: var(--quaternary)"></dd>
                  <dt class="col-sm-3">About Me:</dt>
                  <dd class="col-sm-9" style="color: var(--quaternary)"></dd>
                </dl>
              </div>
            </div>
            <h4 class="text-center">Payrolls</h4>
            <hr style="background-color: var(--secondary)">
            <div class="row">
              <div class="col-12 table-responsive">
                <table class="table table-hover bg-white" id="showEmployeeTable">
                    <thead class="text-center">
                        <tr>
                            <th>Date Issued</th>
                            <th>Overtime</th>  
                            <th>Hours</th>
                            <th>Rate</th>
                            <th>Gross</th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                    </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>