routes/web.php
<?php

use App\Http\Controllers\DepartmentsController;
use App\Http\Controllers\EmployeesController;
use App\Http\Controllers\PayrollsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\UsersController;
use App\Models\Department;
use App\Models\Employee;
use App\Models\Payroll;
use App\Models\Role;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::middleware(['auth'])->group(function() {
    Route::get('/dashboard', function() {
        return view('dashboard', [
            'payrollsCount' => Payroll::all()->count(),
            'employeesCount' => Employee::all()->count(),
            'rolesCount' => Role::all()->count(),
            'departmentsCount' => Department::all()->count(),
            'latestEmployees' => Employee::latest()->take(5)->get(),
            'latestPayrolls' => Payroll::latest()->take(5)->get()
        ]);
    })->name('dashboard')->middleware(['dashboard']);
    Route::resource('departments', DepartmentsController::class)->except(['create', 'show', 'edit'])->middleware(['departments']);
    Route::resource('roles', RolesController::class)->except(['create', 'show', 'edit'])->middleware(['roles']);
    Route::middleware(['employees'])->group(function() {
        Route::put('employees/edit-bulk', [EmployeesController::class, 'updateBulk'])->name('employees.edit.bulk');
        Route::delete('employees/delete-bulk', [EmployeesController::class, 'destroyBulk'])->name('employees.destroy.bulk');
        Route::resource('employees', EmployeesController::class)->except(['create', 'show', 'edit']);
    });
    Route::resource('users', UsersController::class)->only(['update']);
    Route::get('profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::post('profile/update/avatar', [ProfileController::class, 'updateAvatar'])->name('profile.update.avatar');
    Route::put('profile/update', [ProfileController::class, 'update'])->name('profile.update');
    Route::apiResource('payrolls', PayrollsController::class)->only(['update', 'destroy']);
});

app/Models/Role.php
<?php

namespace App\Models;

use App\Http\Traits\UsesUuid;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Role extends Model
{
    use HasFactory, SoftDeletes, UsesUuid;

    protected $guarded = [];
    protected $primaryKey = 'id';

    public function users() {
        return $this->hasMany(User::class, 'role', 'title');
    }

    public function setTitleAttribute($value) {
        $this->attributes['title'] = Str::upper($value);
    }

    public function getTitleAttribute($value) {
        return Str::ucfirst(Str::lower($value));
    }
}

app/Http/Controllers/RolesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class RolesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('roles.index', [
            'roles' => Role::with('users.employee')->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make(
            $request->only('createTitle', 'createDescription'),
            [
                'createTitle' => 'required|string|unique:roles,title',
                'createDescription' => 'sometimes'
            ],
            [],
            [
                'createTitle' => 'title',
                'createDescription' => 'description'
            ]
        )->validate();

        Role::create([
            'title' => $request->createTitle,
            'description' => $request->createDescription
        ]);

        return redirect(route('roles.index'))->with('alert', [
            'type' => 'success',
            'message' => 'Role successfully created!'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        Validator::make(
            $request->only('editTitle', 'editDescription'),
            [
                'editTitle' => 'required|string',
                'editDescription' => 'sometimes'
            ],
            [],
            [
                'editTitle' => 'title',
                'editDescription' => 'description'
            ]
        )->validate();

        $role->update([
            'title' => $request->editTitle,
            'description' => $request->editDescription
        ]);

        return redirect(route('roles.index'))->with('alert', [
            'type' => 'success',
            'message' => 'Role successfully updated!'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->delete();
    }
}

resources/views/roles/create.blade.php
<div class="modal fade" id="createRoleModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header" style="background-color: var(--secondary) !important">
          <h4 class="modal-title">New Role</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{{route('roles.store')}}" method="POST" class="container">
            @csrf
            <div class="modal-body">
                <div class="form-group row">
                    <label for="createTitle" class="col-sm-2 col-form-label">Title:</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" id="createTitle" name="createTitle" value="{{old('createTitle')}}">
                      @error('createTitle')
                        <span class="text-danger small" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                      @enderror
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="form-group">
                          <label>Description (Optional):</label>
                          <textarea class="form-control" rows="4"
                              placeholder="About the Role ..." name="createDescription">{{old('createDescription')}}</textarea>
                          @error('createDescription')
                            <span class="text-danger small" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                          @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn button">
                    Submit
                </button>
            </div>
        </form>
      </div>
    </div>
  </div>

resources/views/roles/edit.blade.php
<div class="modal fade" id="editRoleModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header bg-gradient-warning">
          <h4 class="modal-title">Edit Role</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="" method="POST" class="container" id="editRoleForm">
            @csrf
            @method('PUT')
            <div class="modal-body">
                <div class="form-group row">
                    <label for="editTitle" class="col-sm-2 col-form-label">Title:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="editTitle" name="editTitle" readonly>
                        @error('editTitle')
                            <span class="text-danger small" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="form-group">
                            <label>Description (Optional):</label>
                            <textarea class="form-control" rows="4"
                                placeholder="About the Role ..." name="editDescription" id="editDescription"></textarea>
                            @error('editDescription')
                                <span class="text-danger small" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-warning">
                    Submit
                </button>
            </div>
        </form>
      </div>
    </div>
  </div>

resources/views/roles/index.blade.php
@extends('layouts.app')

@section('title')
Empayroll | Roles
@stop

@section('header_title')
<h1 class="m-0" style="color: var(--primary)">Roles</h1>
<hr style="background-color: var(--primary)">
@stop

@section('content')

@include('roles.create')
@include('roles.show')
@include('roles.edit')

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    @if(in_array(auth()->user()->role, ['Tester', 'Admin']))
                        <button class="btn float-right button rounded-pill" data-toggle="modal"
                            data-target="#createRoleModal">
                            Create New
                        </button>
                    @endif
                </div>
                <div class="card-body table-responsive">
                    <table class="table table-hover bg-white" id="rolesTable">
                        <thead class="text-center">
                            <tr>
                                <th>Title</th>
                                <th>Users Count</th>
                                <th>Description</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                            @foreach($roles as $role)
                                <tr>
                                    <td>{{$role->title}}</td>
                                    <td>{{$role->users->count()}}</td>
                                    <td>
                                        @if(Str::length($role->description) > 50)
                                            {{Str::limit($role->description, 50)}}
                                        @else
                                            @isset($role->description)
                                                {{$role->description}}
                                            @endisset
                                            @empty($role->description)
                                                No description has been provided for this role
                                            @endempty
                                        @endif
                                    </td>
                                    <td>
                                        <span data-toggle="tooltip" data-placement="top" title="View">
                                            <button class="btn btn-primary rounded-circle mx-1 btn-sm"
                                                data-toggle="modal" data-target="#showRoleModal"
                                                onclick="showRole('{{$role->id}}')">
                                                <i class="far fa-eye"></i>
                                            </button>
                                        </span>
                                        @if(in_array(auth()->user()->role, ['Tester', 'Admin']))
                                            <span data-toggle="tooltip" data-placement="top" title="Edit">
                                                <button class="btn btn-warning rounded-circle mx-1 btn-sm"
                                                    data-toggle="modal" data-target="#editRoleModal"
                                                    onclick="editRole('{{$role->id}}')">
                                                    <i class="far fa-edit"></i>
                                                </button>
                                            </span>
                                            <span data-toggle="tooltip" data-placement="top" title="Delete">
                                                <button class="btn btn-danger rounded-circle mx-1 btn-sm"
                                                    onclick="deleteRole('{{$role->id}}')">
                                                    <i class="far fa-trash-alt"></i>
                                                </button>
                                            </span>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('scripts')
<script>
    function showRole(id) {
        let roles = {!! $roles !!};
        let role = roles.find(role => role.id == id);
        $('#showRoleInfo dd:first').text(role.title);
        $('#showRoleInfo dd:last').text(role.description);
        $('#showRoleTable').DataTable().clear().destroy();
        role.users.forEach(user => {
            $('#showRoleTable tbody').append('<tr>' + 
                '<td>' + user.created_at + '</td>' +
                '<td>' + user.name + '</td>' +
                '<td>' + user.email + '</td>' +
                '<td>' + user.employee.position + '</td>' +
            '</tr>')
        });
        $('#showRoleTable').DataTable();
    }

    function editRole(id) {
        let roles = {!! $roles !!};
        role = roles.find(role => role.id == id);
        $('#editTitle').val(role.title);
        $('#editDescription').val(role.description);
        $('#editRoleForm').attr('action', '{{route('home')}}' + '/roles/' + id);
    }

    function deleteRole(id) {
        Swal.fire({
            title: 'Are you sure?',
            text: "Only privileged users can revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3d5af1',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.value) {
                axios.delete('{{route('home')}}' + '/roles/' + id).then(() => {
                    Swal.fire(
                        'Deleted!',
                        'Role has been deleted.',
                        'success'
                    )
                    location.reload();
                });
            }
        })
    }

    $('#rolesTable').DataTable();
</script>
@stop

resources/views/roles/show.blade.php
<div class="modal fade" id="showRoleModal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header bg-primary">
          <h4 class="modal-title">View Role</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="container">
            <h4 class="text-center">Details</h4>
            <hr style="background-color: var(--secondary)">
            <dl class="row mx-5" id="showRoleInfo">
              <dt class="col-sm-2">Title:</dt>
              <dd class="col-sm-10" style="color: var(--quaternary)"></dd>
              <dt class="col-sm-2">Description:</dt>
              <dd class="col-sm-10" style="color: var(--quaternary)"></dd>
            </dl>
            <h4 class="text-center">Users</h4>
            <hr style="background-color: var(--secondary)">
            <div class="row">
              <div class="col-12 table-responsive">
                <table class="table table-hover bg-white" id="showRoleTable">
                    <thead class="text-center">
                        <tr>
                            <th>Date Added</th>
                            <th>Name</th>
                            <th>Email</th>  
                            <th>Position</th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                    </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>